name: Clank
main: hototya\item\Clank
version: 1.0.2
api: 3.9.0

load: POSTWORLD
author: hototya
authors:
- deceitya
description: hototyaのアイテムガチャプラグイン修正版
website: https://github.com/deceitya/Clank

depend:
- EconomyAPI

permissions:
  clankplugin.command.*:
    description: Allows the user to run a command of ClankPlugin
    default: true
    children:
      clankplugin.command.clank:
        description: Allows the user to run the clank command
        default: true
      clankplugin.command.aclank:
        description: Allows the user to run the aclank command
        default: op